# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Quik Logik
email: logik1286@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  High performance computing in your own home
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://quiklogik.com" # the base hostname & protocol for your site
github_username:  logik1286

# Build settings
markdown: kramdown
gems: 
  - jekyll-redirect-from
